### ISSUE TITLE
The problem with the schedule from Modeus

### ISSUE THREAD

**Issue by bereznyak72** [depocoder/YetAnotherCalendar#37]
If a person does not study in netology, then the api/modeus/events/ method returns only lessons in a Yandex telemost, it does not return others lessons

**Comment by depocoder** [comment]
Need more information

**Comment by bereznyak72** [comment]
Lessons that take place in the buildings of UTMN are not returned, only online lessons

**Comment by depocoder** [comment]
> Lessons that take place in the buildings of UTMN are not returned, only online lessons

The goal of this project is to create a Calendar for UTMN + Netology students ONLY. Not for UTMN students. Please fork repo, and commit changes in your repo.

I don't know if we merge your repo to our, btw.
